// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI0_n8A7BwvITIq0whVs9So1pqySwl-UE',
    appId: '1:266791598182:web:81b4559f7fc1c7731555a7',
    messagingSenderId: '266791598182',
    projectId: 'todo-739a2',
    authDomain: 'todo-739a2.firebaseapp.com',
    storageBucket: 'todo-739a2.firebasestorage.app',
    measurementId: 'G-SVJ2MFVEC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhmZH6JAl3sQcNoF25VkcONYKGdzQWuk',
    appId: '1:266791598182:android:59f1b65a3ccf8b7a1555a7',
    messagingSenderId: '266791598182',
    projectId: 'todo-739a2',
    storageBucket: 'todo-739a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_XLMo6xqJTXNpzMULo9CXPJWPp1opow',
    appId: '1:266791598182:ios:0fff8d1c80a4ffc01555a7',
    messagingSenderId: '266791598182',
    projectId: 'todo-739a2',
    storageBucket: 'todo-739a2.firebasestorage.app',
    iosBundleId: 'com.example.todoHassan',
  );
}
